keep_joints:
  - x_taxel_0_01_uspr2f_01_joint
  - x_taxel_0_01_uspr2f_02_joint
  - x_taxel_0_01_uspr2f_03_joint
  - x_taxel_0_01_uspr2f_04_joint
  - x_taxel_0_01_uspr2f_05_joint
  - x_taxel_0_01_uspr2f_06_joint
  - x_taxel_0_01_uspr2f_07_joint
  - x_taxel_0_01_uspr2f_08_joint
  - x_taxel_0_01_uspr2f_09_joint
  - x_taxel_0_01_uspr2f_10_joint
  - x_taxel_0_01_uspr2f_11_joint
  - x_taxel_0_01_uspr2f_12_joint
  - x_taxel_0_01_uspr2f_13_joint
  - x_taxel_0_01_uspr2f_14_joint
  - x_taxel_0_01_uspr2f_15_joint
  - x_taxel_0_01_uspr2f_16_joint
  - x_taxel_0_01_uspr2f_17_joint
  - x_taxel_0_01_uspr2f_18_joint
  - x_taxel_0_01_uspr2f_19_joint
  - x_taxel_0_01_uspr2f_20_joint
  - x_taxel_0_01_uspr2f_21_joint
  - x_taxel_0_01_uspr2f_22_joint
  - x_taxel_0_01_uspr2f_23_joint
  - x_taxel_0_01_uspr2f_24_joint
  - x_taxel_0_02_uspr2f_01_joint
  - x_taxel_0_02_uspr2f_02_joint
  - x_taxel_0_02_uspr2f_03_joint
  - x_taxel_0_02_uspr2f_04_joint
  - x_taxel_0_02_uspr2f_05_joint
  - x_taxel_0_02_uspr2f_06_joint
  - x_taxel_0_02_uspr2f_07_joint
  - x_taxel_0_02_uspr2f_08_joint
  - x_taxel_0_02_uspr2f_09_joint
  - x_taxel_0_02_uspr2f_10_joint
  - x_taxel_0_02_uspr2f_11_joint
  - x_taxel_0_02_uspr2f_12_joint
  - x_taxel_0_02_uspr2f_13_joint
  - x_taxel_0_02_uspr2f_14_joint
  - x_taxel_0_02_uspr2f_15_joint
  - x_taxel_0_02_uspr2f_16_joint
  - x_taxel_0_02_uspr2f_17_joint
  - x_taxel_0_02_uspr2f_18_joint
  - x_taxel_0_02_uspr2f_19_joint
  - x_taxel_0_02_uspr2f_20_joint
  - x_taxel_0_02_uspr2f_21_joint
  - x_taxel_0_02_uspr2f_22_joint
  - x_taxel_0_02_uspr2f_23_joint
  - x_taxel_0_02_uspr2f_24_joint
