keep_joints:
  - x_taxel_0_01_4x4_01_joint
  - x_taxel_0_01_4x4_02_joint
  - x_taxel_0_01_4x4_03_joint
  - x_taxel_0_01_4x4_04_joint
  - x_taxel_0_01_4x4_05_joint
  - x_taxel_0_01_4x4_06_joint
  - x_taxel_0_01_4x4_07_joint
  - x_taxel_0_01_4x4_08_joint
  - x_taxel_0_01_4x4_09_joint
  - x_taxel_0_01_4x4_10_joint
  - x_taxel_0_01_4x4_11_joint
  - x_taxel_0_01_4x4_12_joint
  - x_taxel_0_01_4x4_13_joint
  - x_taxel_0_01_4x4_14_joint
  - x_taxel_0_01_4x4_15_joint
  - x_taxel_0_01_4x4_16_joint
  - x_taxel_0_02_4x4_01_joint
  - x_taxel_0_02_4x4_02_joint
  - x_taxel_0_02_4x4_03_joint
  - x_taxel_0_02_4x4_04_joint
  - x_taxel_0_02_4x4_05_joint
  - x_taxel_0_02_4x4_06_joint
  - x_taxel_0_02_4x4_07_joint
  - x_taxel_0_02_4x4_08_joint
  - x_taxel_0_02_4x4_09_joint
  - x_taxel_0_02_4x4_10_joint
  - x_taxel_0_02_4x4_11_joint
  - x_taxel_0_02_4x4_12_joint
  - x_taxel_0_02_4x4_13_joint
  - x_taxel_0_02_4x4_14_joint
  - x_taxel_0_02_4x4_15_joint
  - x_taxel_0_02_4x4_16_joint
  - x_taxel_0_03_aftc_01_joint
  - x_taxel_0_03_aftc_02_joint
  - x_taxel_0_03_aftc_03_joint
  - x_taxel_0_03_aftc_04_joint
  - x_taxel_0_03_aftc_05_joint
  - x_taxel_0_03_aftc_06_joint
  - x_taxel_0_03_aftc_07_joint
  - x_taxel_0_03_aftc_08_joint
  - x_taxel_0_03_aftc_09_joint
  - x_taxel_0_03_aftc_10_joint
  - x_taxel_0_03_aftc_11_joint
  - x_taxel_0_03_aftc_12_joint
  - x_taxel_0_03_aftc_13_joint
  - x_taxel_0_03_aftc_14_joint
  - x_taxel_0_03_aftc_15_joint
  - x_taxel_0_03_aftc_16_joint
  - x_taxel_0_03_aftc_17_joint
  - x_taxel_0_03_aftc_18_joint
  - x_taxel_0_03_aftc_19_joint
  - x_taxel_0_03_aftc_20_joint
  - x_taxel_0_03_aftc_21_joint
  - x_taxel_0_03_aftc_22_joint
  - x_taxel_0_03_aftc_23_joint
  - x_taxel_0_03_aftc_24_joint
  - x_taxel_0_03_aftc_25_joint
  - x_taxel_0_03_aftc_26_joint
  - x_taxel_0_03_aftc_27_joint
  - x_taxel_0_03_aftc_28_joint
  - x_taxel_0_03_aftc_29_joint
  - x_taxel_0_03_aftc_30_joint
  - x_taxel_0_10_4x4_01_joint
  - x_taxel_0_10_4x4_02_joint
  - x_taxel_0_10_4x4_03_joint
  - x_taxel_0_10_4x4_04_joint
  - x_taxel_0_10_4x4_05_joint
  - x_taxel_0_10_4x4_06_joint
  - x_taxel_0_10_4x4_07_joint
  - x_taxel_0_10_4x4_08_joint
  - x_taxel_0_10_4x4_09_joint
  - x_taxel_0_10_4x4_10_joint
  - x_taxel_0_10_4x4_11_joint
  - x_taxel_0_10_4x4_12_joint
  - x_taxel_0_10_4x4_13_joint
  - x_taxel_0_10_4x4_14_joint
  - x_taxel_0_10_4x4_15_joint
  - x_taxel_0_10_4x4_16_joint
  - x_taxel_0_11_4x4_01_joint
  - x_taxel_0_11_4x4_02_joint
  - x_taxel_0_11_4x4_03_joint
  - x_taxel_0_11_4x4_04_joint
  - x_taxel_0_11_4x4_05_joint
  - x_taxel_0_11_4x4_06_joint
  - x_taxel_0_11_4x4_07_joint
  - x_taxel_0_11_4x4_08_joint
  - x_taxel_0_11_4x4_09_joint
  - x_taxel_0_11_4x4_10_joint
  - x_taxel_0_11_4x4_11_joint
  - x_taxel_0_11_4x4_12_joint
  - x_taxel_0_11_4x4_13_joint
  - x_taxel_0_11_4x4_14_joint
  - x_taxel_0_11_4x4_15_joint
  - x_taxel_0_11_4x4_16_joint
  - x_taxel_0_12_4x4_01_joint
  - x_taxel_0_12_4x4_02_joint
  - x_taxel_0_12_4x4_03_joint
  - x_taxel_0_12_4x4_04_joint
  - x_taxel_0_12_4x4_05_joint
  - x_taxel_0_12_4x4_06_joint
  - x_taxel_0_12_4x4_07_joint
  - x_taxel_0_12_4x4_08_joint
  - x_taxel_0_12_4x4_09_joint
  - x_taxel_0_12_4x4_10_joint
  - x_taxel_0_12_4x4_11_joint
  - x_taxel_0_12_4x4_12_joint
  - x_taxel_0_12_4x4_13_joint
  - x_taxel_0_12_4x4_14_joint
  - x_taxel_0_12_4x4_15_joint
  - x_taxel_0_12_4x4_16_joint
  - x_taxel_0_13_aftc_01_joint
  - x_taxel_0_13_aftc_02_joint
  - x_taxel_0_13_aftc_03_joint
  - x_taxel_0_13_aftc_04_joint
  - x_taxel_0_13_aftc_05_joint
  - x_taxel_0_13_aftc_06_joint
  - x_taxel_0_13_aftc_07_joint
  - x_taxel_0_13_aftc_08_joint
  - x_taxel_0_13_aftc_09_joint
  - x_taxel_0_13_aftc_10_joint
  - x_taxel_0_13_aftc_11_joint
  - x_taxel_0_13_aftc_12_joint
  - x_taxel_0_13_aftc_13_joint
  - x_taxel_0_13_aftc_14_joint
  - x_taxel_0_13_aftc_15_joint
  - x_taxel_0_13_aftc_16_joint
  - x_taxel_0_13_aftc_17_joint
  - x_taxel_0_13_aftc_18_joint
  - x_taxel_0_13_aftc_19_joint
  - x_taxel_0_13_aftc_20_joint
  - x_taxel_0_13_aftc_21_joint
  - x_taxel_0_13_aftc_22_joint
  - x_taxel_0_13_aftc_23_joint
  - x_taxel_0_13_aftc_24_joint
  - x_taxel_0_13_aftc_25_joint
  - x_taxel_0_13_aftc_26_joint
  - x_taxel_0_13_aftc_27_joint
  - x_taxel_0_13_aftc_28_joint
  - x_taxel_0_13_aftc_29_joint
  - x_taxel_0_13_aftc_30_joint
  - x_taxel_0_20_4x4_01_joint
  - x_taxel_0_20_4x4_02_joint
  - x_taxel_0_20_4x4_03_joint
  - x_taxel_0_20_4x4_04_joint
  - x_taxel_0_20_4x4_05_joint
  - x_taxel_0_20_4x4_06_joint
  - x_taxel_0_20_4x4_07_joint
  - x_taxel_0_20_4x4_08_joint
  - x_taxel_0_20_4x4_09_joint
  - x_taxel_0_20_4x4_10_joint
  - x_taxel_0_20_4x4_11_joint
  - x_taxel_0_20_4x4_12_joint
  - x_taxel_0_20_4x4_13_joint
  - x_taxel_0_20_4x4_14_joint
  - x_taxel_0_20_4x4_15_joint
  - x_taxel_0_20_4x4_16_joint
  - x_taxel_0_21_4x4_01_joint
  - x_taxel_0_21_4x4_02_joint
  - x_taxel_0_21_4x4_03_joint
  - x_taxel_0_21_4x4_04_joint
  - x_taxel_0_21_4x4_05_joint
  - x_taxel_0_21_4x4_06_joint
  - x_taxel_0_21_4x4_07_joint
  - x_taxel_0_21_4x4_08_joint
  - x_taxel_0_21_4x4_09_joint
  - x_taxel_0_21_4x4_10_joint
  - x_taxel_0_21_4x4_11_joint
  - x_taxel_0_21_4x4_12_joint
  - x_taxel_0_21_4x4_13_joint
  - x_taxel_0_21_4x4_14_joint
  - x_taxel_0_21_4x4_15_joint
  - x_taxel_0_21_4x4_16_joint
  - x_taxel_0_22_4x4_01_joint
  - x_taxel_0_22_4x4_02_joint
  - x_taxel_0_22_4x4_03_joint
  - x_taxel_0_22_4x4_04_joint
  - x_taxel_0_22_4x4_05_joint
  - x_taxel_0_22_4x4_06_joint
  - x_taxel_0_22_4x4_07_joint
  - x_taxel_0_22_4x4_08_joint
  - x_taxel_0_22_4x4_09_joint
  - x_taxel_0_22_4x4_10_joint
  - x_taxel_0_22_4x4_11_joint
  - x_taxel_0_22_4x4_12_joint
  - x_taxel_0_22_4x4_13_joint
  - x_taxel_0_22_4x4_14_joint
  - x_taxel_0_22_4x4_15_joint
  - x_taxel_0_22_4x4_16_joint
  - x_taxel_0_23_aftc_01_joint
  - x_taxel_0_23_aftc_02_joint
  - x_taxel_0_23_aftc_03_joint
  - x_taxel_0_23_aftc_04_joint
  - x_taxel_0_23_aftc_05_joint
  - x_taxel_0_23_aftc_06_joint
  - x_taxel_0_23_aftc_07_joint
  - x_taxel_0_23_aftc_08_joint
  - x_taxel_0_23_aftc_09_joint
  - x_taxel_0_23_aftc_10_joint
  - x_taxel_0_23_aftc_11_joint
  - x_taxel_0_23_aftc_12_joint
  - x_taxel_0_23_aftc_13_joint
  - x_taxel_0_23_aftc_14_joint
  - x_taxel_0_23_aftc_15_joint
  - x_taxel_0_23_aftc_16_joint
  - x_taxel_0_23_aftc_17_joint
  - x_taxel_0_23_aftc_18_joint
  - x_taxel_0_23_aftc_19_joint
  - x_taxel_0_23_aftc_20_joint
  - x_taxel_0_23_aftc_21_joint
  - x_taxel_0_23_aftc_22_joint
  - x_taxel_0_23_aftc_23_joint
  - x_taxel_0_23_aftc_24_joint
  - x_taxel_0_23_aftc_25_joint
  - x_taxel_0_23_aftc_26_joint
  - x_taxel_0_23_aftc_27_joint
  - x_taxel_0_23_aftc_28_joint
  - x_taxel_0_23_aftc_29_joint
  - x_taxel_0_23_aftc_30_joint
  - x_taxel_0_30_4x4_01_joint
  - x_taxel_0_30_4x4_02_joint
  - x_taxel_0_30_4x4_03_joint
  - x_taxel_0_30_4x4_04_joint
  - x_taxel_0_30_4x4_05_joint
  - x_taxel_0_30_4x4_06_joint
  - x_taxel_0_30_4x4_07_joint
  - x_taxel_0_30_4x4_08_joint
  - x_taxel_0_30_4x4_09_joint
  - x_taxel_0_30_4x4_10_joint
  - x_taxel_0_30_4x4_11_joint
  - x_taxel_0_30_4x4_12_joint
  - x_taxel_0_30_4x4_13_joint
  - x_taxel_0_30_4x4_14_joint
  - x_taxel_0_30_4x4_15_joint
  - x_taxel_0_30_4x4_16_joint
  - x_taxel_0_31_4x4_01_joint
  - x_taxel_0_31_4x4_02_joint
  - x_taxel_0_31_4x4_03_joint
  - x_taxel_0_31_4x4_04_joint
  - x_taxel_0_31_4x4_05_joint
  - x_taxel_0_31_4x4_06_joint
  - x_taxel_0_31_4x4_07_joint
  - x_taxel_0_31_4x4_08_joint
  - x_taxel_0_31_4x4_09_joint
  - x_taxel_0_31_4x4_10_joint
  - x_taxel_0_31_4x4_11_joint
  - x_taxel_0_31_4x4_12_joint
  - x_taxel_0_31_4x4_13_joint
  - x_taxel_0_31_4x4_14_joint
  - x_taxel_0_31_4x4_15_joint
  - x_taxel_0_31_4x4_16_joint
  - x_taxel_0_32_4x4_01_joint
  - x_taxel_0_32_4x4_02_joint
  - x_taxel_0_32_4x4_03_joint
  - x_taxel_0_32_4x4_04_joint
  - x_taxel_0_32_4x4_05_joint
  - x_taxel_0_32_4x4_06_joint
  - x_taxel_0_32_4x4_07_joint
  - x_taxel_0_32_4x4_08_joint
  - x_taxel_0_32_4x4_09_joint
  - x_taxel_0_32_4x4_10_joint
  - x_taxel_0_32_4x4_11_joint
  - x_taxel_0_32_4x4_12_joint
  - x_taxel_0_32_4x4_13_joint
  - x_taxel_0_32_4x4_14_joint
  - x_taxel_0_32_4x4_15_joint
  - x_taxel_0_32_4x4_16_joint
  - x_taxel_0_33_aftc_01_joint
  - x_taxel_0_33_aftc_02_joint
  - x_taxel_0_33_aftc_03_joint
  - x_taxel_0_33_aftc_04_joint
  - x_taxel_0_33_aftc_05_joint
  - x_taxel_0_33_aftc_06_joint
  - x_taxel_0_33_aftc_07_joint
  - x_taxel_0_33_aftc_08_joint
  - x_taxel_0_33_aftc_09_joint
  - x_taxel_0_33_aftc_10_joint
  - x_taxel_0_33_aftc_11_joint
  - x_taxel_0_33_aftc_12_joint
  - x_taxel_0_33_aftc_13_joint
  - x_taxel_0_33_aftc_14_joint
  - x_taxel_0_33_aftc_15_joint
  - x_taxel_0_33_aftc_16_joint
  - x_taxel_0_33_aftc_17_joint
  - x_taxel_0_33_aftc_18_joint
  - x_taxel_0_33_aftc_19_joint
  - x_taxel_0_33_aftc_20_joint
  - x_taxel_0_33_aftc_21_joint
  - x_taxel_0_33_aftc_22_joint
  - x_taxel_0_33_aftc_23_joint
  - x_taxel_0_33_aftc_24_joint
  - x_taxel_0_33_aftc_25_joint
  - x_taxel_0_33_aftc_26_joint
  - x_taxel_0_33_aftc_27_joint
  - x_taxel_0_33_aftc_28_joint
  - x_taxel_0_33_aftc_29_joint
  - x_taxel_0_33_aftc_30_joint
  - x_taxel_0_51_4x6_01_joint
  - x_taxel_0_51_4x6_02_joint
  - x_taxel_0_51_4x6_03_joint
  - x_taxel_0_51_4x6_04_joint
  - x_taxel_0_51_4x6_05_joint
  - x_taxel_0_51_4x6_06_joint
  - x_taxel_0_51_4x6_07_joint
  - x_taxel_0_51_4x6_08_joint
  - x_taxel_0_51_4x6_09_joint
  - x_taxel_0_51_4x6_10_joint
  - x_taxel_0_51_4x6_11_joint
  - x_taxel_0_51_4x6_12_joint
  - x_taxel_0_51_4x6_13_joint
  - x_taxel_0_51_4x6_14_joint
  - x_taxel_0_51_4x6_15_joint
  - x_taxel_0_51_4x6_16_joint
  - x_taxel_0_51_4x6_17_joint
  - x_taxel_0_51_4x6_18_joint
  - x_taxel_0_51_4x6_19_joint
  - x_taxel_0_51_4x6_20_joint
  - x_taxel_0_51_4x6_21_joint
  - x_taxel_0_51_4x6_22_joint
  - x_taxel_0_51_4x6_23_joint
  - x_taxel_0_51_4x6_24_joint
  - x_taxel_0_52_4x6_01_joint
  - x_taxel_0_52_4x6_02_joint
  - x_taxel_0_52_4x6_03_joint
  - x_taxel_0_52_4x6_04_joint
  - x_taxel_0_52_4x6_05_joint
  - x_taxel_0_52_4x6_06_joint
  - x_taxel_0_52_4x6_07_joint
  - x_taxel_0_52_4x6_08_joint
  - x_taxel_0_52_4x6_09_joint
  - x_taxel_0_52_4x6_10_joint
  - x_taxel_0_52_4x6_11_joint
  - x_taxel_0_52_4x6_12_joint
  - x_taxel_0_52_4x6_13_joint
  - x_taxel_0_52_4x6_14_joint
  - x_taxel_0_52_4x6_15_joint
  - x_taxel_0_52_4x6_16_joint
  - x_taxel_0_52_4x6_17_joint
  - x_taxel_0_52_4x6_18_joint
  - x_taxel_0_52_4x6_19_joint
  - x_taxel_0_52_4x6_20_joint
  - x_taxel_0_52_4x6_21_joint
  - x_taxel_0_52_4x6_22_joint
  - x_taxel_0_52_4x6_23_joint
  - x_taxel_0_52_4x6_24_joint
  - x_taxel_0_53_4x6_01_joint
  - x_taxel_0_53_4x6_02_joint
  - x_taxel_0_53_4x6_03_joint
  - x_taxel_0_53_4x6_04_joint
  - x_taxel_0_53_4x6_05_joint
  - x_taxel_0_53_4x6_06_joint
  - x_taxel_0_53_4x6_07_joint
  - x_taxel_0_53_4x6_08_joint
  - x_taxel_0_53_4x6_09_joint
  - x_taxel_0_53_4x6_10_joint
  - x_taxel_0_53_4x6_11_joint
  - x_taxel_0_53_4x6_12_joint
  - x_taxel_0_53_4x6_13_joint
  - x_taxel_0_53_4x6_14_joint
  - x_taxel_0_53_4x6_15_joint
  - x_taxel_0_53_4x6_16_joint
  - x_taxel_0_53_4x6_17_joint
  - x_taxel_0_53_4x6_18_joint
  - x_taxel_0_53_4x6_19_joint
  - x_taxel_0_53_4x6_20_joint
  - x_taxel_0_53_4x6_21_joint
  - x_taxel_0_53_4x6_22_joint
  - x_taxel_0_53_4x6_23_joint
  - x_taxel_0_53_4x6_24_joint
