keep_joints:
  - x_taxel_0_01_uSPa44_01_joint
  - x_taxel_0_01_uSPa44_02_joint
  - x_taxel_0_01_uSPa44_03_joint
  - x_taxel_0_01_uSPa44_04_joint
  - x_taxel_0_01_uSPa44_05_joint
  - x_taxel_0_01_uSPa44_06_joint
  - x_taxel_0_01_uSPa44_07_joint
  - x_taxel_0_01_uSPa44_08_joint
  - x_taxel_0_01_uSPa44_09_joint
  - x_taxel_0_01_uSPa44_10_joint
  - x_taxel_0_01_uSPa44_11_joint
  - x_taxel_0_01_uSPa44_12_joint
  - x_taxel_0_01_uSPa44_13_joint
  - x_taxel_0_01_uSPa44_14_joint
  - x_taxel_0_01_uSPa44_15_joint
  - x_taxel_0_01_uSPa44_16_joint
  - x_taxel_0_02_uSPa44_01_joint
  - x_taxel_0_02_uSPa44_02_joint
  - x_taxel_0_02_uSPa44_03_joint
  - x_taxel_0_02_uSPa44_04_joint
  - x_taxel_0_02_uSPa44_05_joint
  - x_taxel_0_02_uSPa44_06_joint
  - x_taxel_0_02_uSPa44_07_joint
  - x_taxel_0_02_uSPa44_08_joint
  - x_taxel_0_02_uSPa44_09_joint
  - x_taxel_0_02_uSPa44_10_joint
  - x_taxel_0_02_uSPa44_11_joint
  - x_taxel_0_02_uSPa44_12_joint
  - x_taxel_0_02_uSPa44_13_joint
  - x_taxel_0_02_uSPa44_14_joint
  - x_taxel_0_02_uSPa44_15_joint
  - x_taxel_0_02_uSPa44_16_joint
  - x_taxel_0_03_uSCuAH_01_joint
  - x_taxel_0_03_uSCuAH_02_joint
  - x_taxel_0_03_uSCuAH_03_joint
  - x_taxel_0_03_uSCuAH_04_joint
  - x_taxel_0_03_uSCuAH_05_joint
  - x_taxel_0_03_uSCuAH_06_joint
  - x_taxel_0_03_uSCuAH_07_joint
  - x_taxel_0_03_uSCuAH_08_joint
  - x_taxel_0_03_uSCuAH_09_joint
  - x_taxel_0_03_uSCuAH_10_joint
  - x_taxel_0_03_uSCuAH_11_joint
  - x_taxel_0_03_uSCuAH_12_joint
  - x_taxel_0_03_uSCuAH_13_joint
  - x_taxel_0_03_uSCuAH_14_joint
  - x_taxel_0_03_uSCuAH_15_joint
  - x_taxel_0_03_uSCuAH_16_joint
  - x_taxel_0_03_uSCuAH_17_joint
  - x_taxel_0_03_uSCuAH_18_joint
  - x_taxel_0_03_uSCuAH_19_joint
  - x_taxel_0_03_uSCuAH_20_joint
  - x_taxel_0_03_uSCuAH_21_joint
  - x_taxel_0_03_uSCuAH_22_joint
  - x_taxel_0_03_uSCuAH_23_joint
  - x_taxel_0_03_uSCuAH_24_joint
  - x_taxel_0_03_uSCuAH_25_joint
  - x_taxel_0_03_uSCuAH_26_joint
  - x_taxel_0_03_uSCuAH_27_joint
  - x_taxel_0_03_uSCuAH_28_joint
  - x_taxel_0_03_uSCuAH_29_joint
  - x_taxel_0_03_uSCuAH_30_joint
  - x_taxel_0_10_uSPa44_01_joint
  - x_taxel_0_10_uSPa44_02_joint
  - x_taxel_0_10_uSPa44_03_joint
  - x_taxel_0_10_uSPa44_04_joint
  - x_taxel_0_10_uSPa44_05_joint
  - x_taxel_0_10_uSPa44_06_joint
  - x_taxel_0_10_uSPa44_07_joint
  - x_taxel_0_10_uSPa44_08_joint
  - x_taxel_0_10_uSPa44_09_joint
  - x_taxel_0_10_uSPa44_10_joint
  - x_taxel_0_10_uSPa44_11_joint
  - x_taxel_0_10_uSPa44_12_joint
  - x_taxel_0_10_uSPa44_13_joint
  - x_taxel_0_10_uSPa44_14_joint
  - x_taxel_0_10_uSPa44_15_joint
  - x_taxel_0_10_uSPa44_16_joint
  - x_taxel_0_11_uSPa44_01_joint
  - x_taxel_0_11_uSPa44_02_joint
  - x_taxel_0_11_uSPa44_03_joint
  - x_taxel_0_11_uSPa44_04_joint
  - x_taxel_0_11_uSPa44_05_joint
  - x_taxel_0_11_uSPa44_06_joint
  - x_taxel_0_11_uSPa44_07_joint
  - x_taxel_0_11_uSPa44_08_joint
  - x_taxel_0_11_uSPa44_09_joint
  - x_taxel_0_11_uSPa44_10_joint
  - x_taxel_0_11_uSPa44_11_joint
  - x_taxel_0_11_uSPa44_12_joint
  - x_taxel_0_11_uSPa44_13_joint
  - x_taxel_0_11_uSPa44_14_joint
  - x_taxel_0_11_uSPa44_15_joint
  - x_taxel_0_11_uSPa44_16_joint
  - x_taxel_0_12_uSPa44_01_joint
  - x_taxel_0_12_uSPa44_02_joint
  - x_taxel_0_12_uSPa44_03_joint
  - x_taxel_0_12_uSPa44_04_joint
  - x_taxel_0_12_uSPa44_05_joint
  - x_taxel_0_12_uSPa44_06_joint
  - x_taxel_0_12_uSPa44_07_joint
  - x_taxel_0_12_uSPa44_08_joint
  - x_taxel_0_12_uSPa44_09_joint
  - x_taxel_0_12_uSPa44_10_joint
  - x_taxel_0_12_uSPa44_11_joint
  - x_taxel_0_12_uSPa44_12_joint
  - x_taxel_0_12_uSPa44_13_joint
  - x_taxel_0_12_uSPa44_14_joint
  - x_taxel_0_12_uSPa44_15_joint
  - x_taxel_0_12_uSPa44_16_joint
  - x_taxel_0_13_uSCuAH_01_joint
  - x_taxel_0_13_uSCuAH_02_joint
  - x_taxel_0_13_uSCuAH_03_joint
  - x_taxel_0_13_uSCuAH_04_joint
  - x_taxel_0_13_uSCuAH_05_joint
  - x_taxel_0_13_uSCuAH_06_joint
  - x_taxel_0_13_uSCuAH_07_joint
  - x_taxel_0_13_uSCuAH_08_joint
  - x_taxel_0_13_uSCuAH_09_joint
  - x_taxel_0_13_uSCuAH_10_joint
  - x_taxel_0_13_uSCuAH_11_joint
  - x_taxel_0_13_uSCuAH_12_joint
  - x_taxel_0_13_uSCuAH_13_joint
  - x_taxel_0_13_uSCuAH_14_joint
  - x_taxel_0_13_uSCuAH_15_joint
  - x_taxel_0_13_uSCuAH_16_joint
  - x_taxel_0_13_uSCuAH_17_joint
  - x_taxel_0_13_uSCuAH_18_joint
  - x_taxel_0_13_uSCuAH_19_joint
  - x_taxel_0_13_uSCuAH_20_joint
  - x_taxel_0_13_uSCuAH_21_joint
  - x_taxel_0_13_uSCuAH_22_joint
  - x_taxel_0_13_uSCuAH_23_joint
  - x_taxel_0_13_uSCuAH_24_joint
  - x_taxel_0_13_uSCuAH_25_joint
  - x_taxel_0_13_uSCuAH_26_joint
  - x_taxel_0_13_uSCuAH_27_joint
  - x_taxel_0_13_uSCuAH_28_joint
  - x_taxel_0_13_uSCuAH_29_joint
  - x_taxel_0_13_uSCuAH_30_joint
  - x_taxel_0_20_uSPa44_01_joint
  - x_taxel_0_20_uSPa44_02_joint
  - x_taxel_0_20_uSPa44_03_joint
  - x_taxel_0_20_uSPa44_04_joint
  - x_taxel_0_20_uSPa44_05_joint
  - x_taxel_0_20_uSPa44_06_joint
  - x_taxel_0_20_uSPa44_07_joint
  - x_taxel_0_20_uSPa44_08_joint
  - x_taxel_0_20_uSPa44_09_joint
  - x_taxel_0_20_uSPa44_10_joint
  - x_taxel_0_20_uSPa44_11_joint
  - x_taxel_0_20_uSPa44_12_joint
  - x_taxel_0_20_uSPa44_13_joint
  - x_taxel_0_20_uSPa44_14_joint
  - x_taxel_0_20_uSPa44_15_joint
  - x_taxel_0_20_uSPa44_16_joint
  - x_taxel_0_21_uSPa44_01_joint
  - x_taxel_0_21_uSPa44_02_joint
  - x_taxel_0_21_uSPa44_03_joint
  - x_taxel_0_21_uSPa44_04_joint
  - x_taxel_0_21_uSPa44_05_joint
  - x_taxel_0_21_uSPa44_06_joint
  - x_taxel_0_21_uSPa44_07_joint
  - x_taxel_0_21_uSPa44_08_joint
  - x_taxel_0_21_uSPa44_09_joint
  - x_taxel_0_21_uSPa44_10_joint
  - x_taxel_0_21_uSPa44_11_joint
  - x_taxel_0_21_uSPa44_12_joint
  - x_taxel_0_21_uSPa44_13_joint
  - x_taxel_0_21_uSPa44_14_joint
  - x_taxel_0_21_uSPa44_15_joint
  - x_taxel_0_21_uSPa44_16_joint
  - x_taxel_0_22_uSPa44_01_joint
  - x_taxel_0_22_uSPa44_02_joint
  - x_taxel_0_22_uSPa44_03_joint
  - x_taxel_0_22_uSPa44_04_joint
  - x_taxel_0_22_uSPa44_05_joint
  - x_taxel_0_22_uSPa44_06_joint
  - x_taxel_0_22_uSPa44_07_joint
  - x_taxel_0_22_uSPa44_08_joint
  - x_taxel_0_22_uSPa44_09_joint
  - x_taxel_0_22_uSPa44_10_joint
  - x_taxel_0_22_uSPa44_11_joint
  - x_taxel_0_22_uSPa44_12_joint
  - x_taxel_0_22_uSPa44_13_joint
  - x_taxel_0_22_uSPa44_14_joint
  - x_taxel_0_22_uSPa44_15_joint
  - x_taxel_0_22_uSPa44_16_joint
  - x_taxel_0_23_uSCuAH_01_joint
  - x_taxel_0_23_uSCuAH_02_joint
  - x_taxel_0_23_uSCuAH_03_joint
  - x_taxel_0_23_uSCuAH_04_joint
  - x_taxel_0_23_uSCuAH_05_joint
  - x_taxel_0_23_uSCuAH_06_joint
  - x_taxel_0_23_uSCuAH_07_joint
  - x_taxel_0_23_uSCuAH_08_joint
  - x_taxel_0_23_uSCuAH_09_joint
  - x_taxel_0_23_uSCuAH_10_joint
  - x_taxel_0_23_uSCuAH_11_joint
  - x_taxel_0_23_uSCuAH_12_joint
  - x_taxel_0_23_uSCuAH_13_joint
  - x_taxel_0_23_uSCuAH_14_joint
  - x_taxel_0_23_uSCuAH_15_joint
  - x_taxel_0_23_uSCuAH_16_joint
  - x_taxel_0_23_uSCuAH_17_joint
  - x_taxel_0_23_uSCuAH_18_joint
  - x_taxel_0_23_uSCuAH_19_joint
  - x_taxel_0_23_uSCuAH_20_joint
  - x_taxel_0_23_uSCuAH_21_joint
  - x_taxel_0_23_uSCuAH_22_joint
  - x_taxel_0_23_uSCuAH_23_joint
  - x_taxel_0_23_uSCuAH_24_joint
  - x_taxel_0_23_uSCuAH_25_joint
  - x_taxel_0_23_uSCuAH_26_joint
  - x_taxel_0_23_uSCuAH_27_joint
  - x_taxel_0_23_uSCuAH_28_joint
  - x_taxel_0_23_uSCuAH_29_joint
  - x_taxel_0_23_uSCuAH_30_joint
  - x_taxel_0_30_uSPa44_01_joint
  - x_taxel_0_30_uSPa44_02_joint
  - x_taxel_0_30_uSPa44_03_joint
  - x_taxel_0_30_uSPa44_04_joint
  - x_taxel_0_30_uSPa44_05_joint
  - x_taxel_0_30_uSPa44_06_joint
  - x_taxel_0_30_uSPa44_07_joint
  - x_taxel_0_30_uSPa44_08_joint
  - x_taxel_0_30_uSPa44_09_joint
  - x_taxel_0_30_uSPa44_10_joint
  - x_taxel_0_30_uSPa44_11_joint
  - x_taxel_0_30_uSPa44_12_joint
  - x_taxel_0_30_uSPa44_13_joint
  - x_taxel_0_30_uSPa44_14_joint
  - x_taxel_0_30_uSPa44_15_joint
  - x_taxel_0_30_uSPa44_16_joint
  - x_taxel_0_31_uSPa44_01_joint
  - x_taxel_0_31_uSPa44_02_joint
  - x_taxel_0_31_uSPa44_03_joint
  - x_taxel_0_31_uSPa44_04_joint
  - x_taxel_0_31_uSPa44_05_joint
  - x_taxel_0_31_uSPa44_06_joint
  - x_taxel_0_31_uSPa44_07_joint
  - x_taxel_0_31_uSPa44_08_joint
  - x_taxel_0_31_uSPa44_09_joint
  - x_taxel_0_31_uSPa44_10_joint
  - x_taxel_0_31_uSPa44_11_joint
  - x_taxel_0_31_uSPa44_12_joint
  - x_taxel_0_31_uSPa44_13_joint
  - x_taxel_0_31_uSPa44_14_joint
  - x_taxel_0_31_uSPa44_15_joint
  - x_taxel_0_31_uSPa44_16_joint
  - x_taxel_0_32_uSPa44_01_joint
  - x_taxel_0_32_uSPa44_02_joint
  - x_taxel_0_32_uSPa44_03_joint
  - x_taxel_0_32_uSPa44_04_joint
  - x_taxel_0_32_uSPa44_05_joint
  - x_taxel_0_32_uSPa44_06_joint
  - x_taxel_0_32_uSPa44_07_joint
  - x_taxel_0_32_uSPa44_08_joint
  - x_taxel_0_32_uSPa44_09_joint
  - x_taxel_0_32_uSPa44_10_joint
  - x_taxel_0_32_uSPa44_11_joint
  - x_taxel_0_32_uSPa44_12_joint
  - x_taxel_0_32_uSPa44_13_joint
  - x_taxel_0_32_uSPa44_14_joint
  - x_taxel_0_32_uSPa44_15_joint
  - x_taxel_0_32_uSPa44_16_joint
  - x_taxel_0_33_uSCuAH_01_joint
  - x_taxel_0_33_uSCuAH_02_joint
  - x_taxel_0_33_uSCuAH_03_joint
  - x_taxel_0_33_uSCuAH_04_joint
  - x_taxel_0_33_uSCuAH_05_joint
  - x_taxel_0_33_uSCuAH_06_joint
  - x_taxel_0_33_uSCuAH_07_joint
  - x_taxel_0_33_uSCuAH_08_joint
  - x_taxel_0_33_uSCuAH_09_joint
  - x_taxel_0_33_uSCuAH_10_joint
  - x_taxel_0_33_uSCuAH_11_joint
  - x_taxel_0_33_uSCuAH_12_joint
  - x_taxel_0_33_uSCuAH_13_joint
  - x_taxel_0_33_uSCuAH_14_joint
  - x_taxel_0_33_uSCuAH_15_joint
  - x_taxel_0_33_uSCuAH_16_joint
  - x_taxel_0_33_uSCuAH_17_joint
  - x_taxel_0_33_uSCuAH_18_joint
  - x_taxel_0_33_uSCuAH_19_joint
  - x_taxel_0_33_uSCuAH_20_joint
  - x_taxel_0_33_uSCuAH_21_joint
  - x_taxel_0_33_uSCuAH_22_joint
  - x_taxel_0_33_uSCuAH_23_joint
  - x_taxel_0_33_uSCuAH_24_joint
  - x_taxel_0_33_uSCuAH_25_joint
  - x_taxel_0_33_uSCuAH_26_joint
  - x_taxel_0_33_uSCuAH_27_joint
  - x_taxel_0_33_uSCuAH_28_joint
  - x_taxel_0_33_uSCuAH_29_joint
  - x_taxel_0_33_uSCuAH_30_joint
  - x_taxel_0_51_uSPa46_01_joint
  - x_taxel_0_51_uSPa46_02_joint
  - x_taxel_0_51_uSPa46_03_joint
  - x_taxel_0_51_uSPa46_04_joint
  - x_taxel_0_51_uSPa46_05_joint
  - x_taxel_0_51_uSPa46_06_joint
  - x_taxel_0_51_uSPa46_07_joint
  - x_taxel_0_51_uSPa46_08_joint
  - x_taxel_0_51_uSPa46_09_joint
  - x_taxel_0_51_uSPa46_10_joint
  - x_taxel_0_51_uSPa46_11_joint
  - x_taxel_0_51_uSPa46_12_joint
  - x_taxel_0_51_uSPa46_13_joint
  - x_taxel_0_51_uSPa46_14_joint
  - x_taxel_0_51_uSPa46_15_joint
  - x_taxel_0_51_uSPa46_16_joint
  - x_taxel_0_51_uSPa46_17_joint
  - x_taxel_0_51_uSPa46_18_joint
  - x_taxel_0_51_uSPa46_19_joint
  - x_taxel_0_51_uSPa46_20_joint
  - x_taxel_0_51_uSPa46_21_joint
  - x_taxel_0_51_uSPa46_22_joint
  - x_taxel_0_51_uSPa46_23_joint
  - x_taxel_0_51_uSPa46_24_joint
  - x_taxel_0_52_uSPa46_01_joint
  - x_taxel_0_52_uSPa46_02_joint
  - x_taxel_0_52_uSPa46_03_joint
  - x_taxel_0_52_uSPa46_04_joint
  - x_taxel_0_52_uSPa46_05_joint
  - x_taxel_0_52_uSPa46_06_joint
  - x_taxel_0_52_uSPa46_07_joint
  - x_taxel_0_52_uSPa46_08_joint
  - x_taxel_0_52_uSPa46_09_joint
  - x_taxel_0_52_uSPa46_10_joint
  - x_taxel_0_52_uSPa46_11_joint
  - x_taxel_0_52_uSPa46_12_joint
  - x_taxel_0_52_uSPa46_13_joint
  - x_taxel_0_52_uSPa46_14_joint
  - x_taxel_0_52_uSPa46_15_joint
  - x_taxel_0_52_uSPa46_16_joint
  - x_taxel_0_52_uSPa46_17_joint
  - x_taxel_0_52_uSPa46_18_joint
  - x_taxel_0_52_uSPa46_19_joint
  - x_taxel_0_52_uSPa46_20_joint
  - x_taxel_0_52_uSPa46_21_joint
  - x_taxel_0_52_uSPa46_22_joint
  - x_taxel_0_52_uSPa46_23_joint
  - x_taxel_0_52_uSPa46_24_joint
  - x_taxel_0_53_uSPa46_01_joint
  - x_taxel_0_53_uSPa46_02_joint
  - x_taxel_0_53_uSPa46_03_joint
  - x_taxel_0_53_uSPa46_04_joint
  - x_taxel_0_53_uSPa46_05_joint
  - x_taxel_0_53_uSPa46_06_joint
  - x_taxel_0_53_uSPa46_07_joint
  - x_taxel_0_53_uSPa46_08_joint
  - x_taxel_0_53_uSPa46_09_joint
  - x_taxel_0_53_uSPa46_10_joint
  - x_taxel_0_53_uSPa46_11_joint
  - x_taxel_0_53_uSPa46_12_joint
  - x_taxel_0_53_uSPa46_13_joint
  - x_taxel_0_53_uSPa46_14_joint
  - x_taxel_0_53_uSPa46_15_joint
  - x_taxel_0_53_uSPa46_16_joint
  - x_taxel_0_53_uSPa46_17_joint
  - x_taxel_0_53_uSPa46_18_joint
  - x_taxel_0_53_uSPa46_19_joint
  - x_taxel_0_53_uSPa46_20_joint
  - x_taxel_0_53_uSPa46_21_joint
  - x_taxel_0_53_uSPa46_22_joint
  - x_taxel_0_53_uSPa46_23_joint
  - x_taxel_0_53_uSPa46_24_joint
