keep_joints:
  - x_taxel_01_uSPa46_01_joint
  - x_taxel_01_uSPa46_02_joint
  - x_taxel_01_uSPa46_03_joint
  - x_taxel_01_uSPa46_04_joint
  - x_taxel_01_uSPa46_05_joint
  - x_taxel_01_uSPa46_06_joint
  - x_taxel_01_uSPa46_07_joint
  - x_taxel_01_uSPa46_08_joint
  - x_taxel_01_uSPa46_09_joint
  - x_taxel_01_uSPa46_10_joint
  - x_taxel_01_uSPa46_11_joint
  - x_taxel_01_uSPa46_12_joint
  - x_taxel_01_uSPa46_13_joint
  - x_taxel_01_uSPa46_14_joint
  - x_taxel_01_uSPa46_15_joint
  - x_taxel_01_uSPa46_16_joint
  - x_taxel_01_uSPa46_17_joint
  - x_taxel_01_uSPa46_18_joint
  - x_taxel_01_uSPa46_19_joint
  - x_taxel_01_uSPa46_20_joint
  - x_taxel_01_uSPa46_21_joint
  - x_taxel_01_uSPa46_22_joint
  - x_taxel_01_uSPa46_23_joint
  - x_taxel_01_uSPa46_24_joint
  - x_taxel_02_uSPa46_01_joint
  - x_taxel_02_uSPa46_02_joint
  - x_taxel_02_uSPa46_03_joint
  - x_taxel_02_uSPa46_04_joint
  - x_taxel_02_uSPa46_05_joint
  - x_taxel_02_uSPa46_06_joint
  - x_taxel_02_uSPa46_07_joint
  - x_taxel_02_uSPa46_08_joint
  - x_taxel_02_uSPa46_09_joint
  - x_taxel_02_uSPa46_10_joint
  - x_taxel_02_uSPa46_11_joint
  - x_taxel_02_uSPa46_12_joint
  - x_taxel_02_uSPa46_13_joint
  - x_taxel_02_uSPa46_14_joint
  - x_taxel_02_uSPa46_15_joint
  - x_taxel_02_uSPa46_16_joint
  - x_taxel_02_uSPa46_17_joint
  - x_taxel_02_uSPa46_18_joint
  - x_taxel_02_uSPa46_19_joint
  - x_taxel_02_uSPa46_20_joint
  - x_taxel_02_uSPa46_21_joint
  - x_taxel_02_uSPa46_22_joint
  - x_taxel_02_uSPa46_23_joint
  - x_taxel_02_uSPa46_24_joint
