keep_joints:
  - x_taxel_01_uSPrDS_f_01_joint
  - x_taxel_01_uSPrDS_f_02_joint
  - x_taxel_01_uSPrDS_f_03_joint
  - x_taxel_01_uSPrDS_f_04_joint
  - x_taxel_01_uSPrDS_f_05_joint
  - x_taxel_01_uSPrDS_f_06_joint
  - x_taxel_01_uSPrDS_f_07_joint
  - x_taxel_01_uSPrDS_f_08_joint
  - x_taxel_01_uSPrDS_f_09_joint
  - x_taxel_01_uSPrDS_f_10_joint
  - x_taxel_01_uSPrDS_f_11_joint
  - x_taxel_01_uSPrDS_f_12_joint
  - x_taxel_01_uSPrDS_f_13_joint
  - x_taxel_01_uSPrDS_f_14_joint
  - x_taxel_01_uSPrDS_f_15_joint
  - x_taxel_01_uSPrDS_f_16_joint
  - x_taxel_01_uSPrDS_f_17_joint
  - x_taxel_01_uSPrDS_f_18_joint
  - x_taxel_01_uSPrDS_f_19_joint
  - x_taxel_01_uSPrDS_f_20_joint
  - x_taxel_01_uSPrDS_r_01_joint
  - x_taxel_01_uSPrDS_r_02_joint
  - x_taxel_01_uSPrDS_r_03_joint
  - x_taxel_01_uSPrDS_r_04_joint
  - x_taxel_01_uSPrDS_r_05_joint
  - x_taxel_01_uSPrDS_r_06_joint
  - x_taxel_01_uSPrDS_r_07_joint
  - x_taxel_01_uSPrDS_r_08_joint
  - x_taxel_01_uSPrDS_r_09_joint
  - x_taxel_01_uSPrDS_r_10_joint
  - x_taxel_02_uSPrDS_f_01_joint
  - x_taxel_02_uSPrDS_f_02_joint
  - x_taxel_02_uSPrDS_f_03_joint
  - x_taxel_02_uSPrDS_f_04_joint
  - x_taxel_02_uSPrDS_f_05_joint
  - x_taxel_02_uSPrDS_f_06_joint
  - x_taxel_02_uSPrDS_f_07_joint
  - x_taxel_02_uSPrDS_f_08_joint
  - x_taxel_02_uSPrDS_f_09_joint
  - x_taxel_02_uSPrDS_f_10_joint
  - x_taxel_02_uSPrDS_f_11_joint
  - x_taxel_02_uSPrDS_f_12_joint
  - x_taxel_02_uSPrDS_f_13_joint
  - x_taxel_02_uSPrDS_f_14_joint
  - x_taxel_02_uSPrDS_f_15_joint
  - x_taxel_02_uSPrDS_f_16_joint
  - x_taxel_02_uSPrDS_f_17_joint
  - x_taxel_02_uSPrDS_f_18_joint
  - x_taxel_02_uSPrDS_f_19_joint
  - x_taxel_02_uSPrDS_f_20_joint
  - x_taxel_02_uSPrDS_r_01_joint
  - x_taxel_02_uSPrDS_r_02_joint
  - x_taxel_02_uSPrDS_r_03_joint
  - x_taxel_02_uSPrDS_r_04_joint
  - x_taxel_02_uSPrDS_r_05_joint
  - x_taxel_02_uSPrDS_r_06_joint
  - x_taxel_02_uSPrDS_r_07_joint
  - x_taxel_02_uSPrDS_r_08_joint
  - x_taxel_02_uSPrDS_r_09_joint
  - x_taxel_02_uSPrDS_r_10_joint
